# -*- coding: utf-8 -*-
"""1BM24CS152_HILL_CLIMBING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HqGGkWJtAco2xYg_Z014JB7HisWPsSqg
"""

import random

# Calculate the cost function: number of pairs of queens attacking each other
def count_attacking_pairs(state):
    attacks = 0
    n = len(state)
    for i in range(n):
        for j in range(i + 1, n):
            # Same row attack
            if state[i] == state[j]:
                attacks += 1
            # Diagonal attack: row difference equals column difference
            elif abs(state[i] - state[j]) == abs(i - j):
                attacks += 1
    return attacks

# Define VALUE to align with the maximization pseudocode (higher value is better)
def get_value(state):
    return -count_attacking_pairs(state)

# Generate all neighbors by swapping the row positions of two queens
def get_highest_valued_successor(state):
    best_neighbor = None
    best_value = float('-inf')
    n = len(state)

    # Generate neighbors by swapping columns i and j
    for i in range(n):
        for j in range(i + 1, n):
            neighbor = list(state)
            # Swap the row positions of the two queens
            neighbor[i], neighbor[j] = neighbor[j], neighbor[i]

            neighbor_tuple = tuple(neighbor)
            neighbor_value = get_value(neighbor_tuple)

            # Keep track of the highest-valued neighbor
            if neighbor_value > best_value:
                best_value = neighbor_value
                best_neighbor = neighbor_tuple

    return best_neighbor, best_value

# Core Hill-Climbing Algorithm
def hill_climbing(initial_state):
    current_state = initial_state
    current_value = get_value(current_state)

    print(f"\nInitial State: {current_state} | Attacking Pairs: {-current_value}")

    step = 1
    while True:
        # neighbor <- a highest-valued successor of current
        neighbor_state, neighbor_value = get_highest_valued_successor(current_state)

        print(f"Step {step}: Highest Neighbor: {neighbor_state} | Attacking Pairs: {-neighbor_value}")

        # if neighbor.VALUE <= current.VALUE then return current.STATE
        if neighbor_value <= current_value:
            return current_state, -current_value

        # current <- neighbor
        current_state = neighbor_state
        current_value = neighbor_value
        step += 1

# Helper function to display the 4x4 chessboard layout
def print_board(state):
    for row in range(4):
        line = []
        for col in range(4):
            if state[col] == row:
                line.append("Q")
            else:
                line.append(".")
        print(" ".join(line))
    print()

# Main Execution
def main():
    print("--- 4-Queens Hill-Climbing Solver ---")
    print("Enter the row index (0 to 3) for the queen in each column (0 to 3).")
    print("Example: 1 3 0 2 (meaning column 0 has queen at row 1, column 1 at row 3, etc.)\n")

    try:
        user_input = input("Enter 4 space-separated values for the initial state: ").split()

        if len(user_input) != 4:
            raise ValueError("You must enter exactly 4 values.")

        # Convert inputs to integers
        initial_state = tuple(map(int, user_input))

        # Validate that values are between 0 and 3
        for val in initial_state:
            if val < 0 or val > 3:
                raise ValueError("Each value must be between 0 and 3.")

        # Run Hill-Climbing with the user-defined state
        final_state, final_attacks = hill_climbing(initial_state)

        print("\n--- Final Result ---")
        if final_attacks == 0:
            print("Success! Found a global maximum (Goal State reached).")
        else:
            print("Stuck! Hit a local maximum or plateau (No better neighbors found via swaps).")

        print(f"Final State Configuration: {final_state}")
        print(f"Remaining Attacking Pairs: {final_attacks}\n")
        print_board(final_state)

    except ValueError as e:
        print(f"\nInput Error: {e}")

if __name__ == "__main__":
    main()